### ISSUE TITLE
Migration from old-style settings to the new ones?

### ISSUE THREAD

**Issue by drdaeman** [Ashald/EnvFile#25]
I've updated plugin today and haven't noticed new EnvFile tab, so thought it's broken (I'm on PyCharm EAP build, so I've assumed things could break quite easily). Thanks to a picture in `README.md`, I've figured it all out, though.

However, "EnvFile" tab was empty, and my `.env` file was only mentioned as `ENV_FILE_PATH=/full/path/to/.env` and `ENV_FILE_IS_ENABLED=true` variables in the vanilla "Environment variables" section (which don't seem to have any effect with the new version).

Maybe it would be a good idea to automatically migrate those to a new-style configuration?

**Comment by ashald** [comment]
I thought about that but such functionality would've added more complexity and I'm not sure it would've worked flawlessly... So I decided to to implement it and add a warning to the README. I understand that it causes some inconvenience but since it's a one-time migration I hope it's not too troublesome.

**Comment by drdaeman** [comment]
Ah, yes, if it's not straightforward then it makes sense. I've just thought previous settings had clean mapping to the new ones.

I've missed readme text when upgrading plugin, only noticed it when the process misbehaved and I found out there are no settings anymore where they used to be, and went to GitHub to ask about this.
