### ISSUE TITLE
Get env from a bash script

### ISSUE THREAD

**Issue by frnhr** [Ashald/EnvFile#5]
Is it possible to get env from Bash script? Basically equivalent to running `source my_env.sh`. Presumably, only variables that are `export`-ed should be used.

my_env.sh:

```
#!/usr/bin/env bash

export DJANGO_SETTINGS_MODULE=myproject.settings

if [ -f something/somewhere ]; then
    export $THAT_THING_IS=there
fi

# etc...
```

**Comment by Ashald** [comment]
Not an expert on security etc but I believe that this may led to execution of 'unexpected' code. OTOH I saw number of cases where people don't mind such a risk. Will see, maybe I will be able to add it as an optional feature that can be enabled separately...

**Comment by RSully** [comment]
I'd love to see this. My .env file is formatted as `export A=B` even though I don't run arbitrary code, just so I can easily `source` it. How do you guys use env files outside of your IDE without `export`?

**Comment by ashald** [comment]
@RSully thank you for the feedback!
I still don't have a feasible way to implement this so for now I cannot promise you that it will become a feature.

Regarding your 2nd question: there are actually 2 ways.
1) Use `foreman` or `honcho` to set environment variables from `.env` files rather than exports in bash script
2) you can achieve the same with a bash 1-liner: `while read -r line; do export $line; done < .env` - it will set you environment variables from the `.env` file in the current dir. Luckily, `.env` format is exactly the same as the syntax for `export`. :)
