### ISSUE TITLE
Allow remote env files

### ISSUE THREAD

**Issue by bedge** [Ashald/EnvFile#51]
For remote debugging, one needs remote env files.

This would some additional plumbing so that the remote env could be sourced by the remote interpreter at load time.

**Comment by ashald** [comment]
Unfortunately, at this point I don't see a way how this can be addressed. This plugin operates within IDEA process rather than "where code is run". And I don't know the IDEA platform enough even to say if it's possible at all or no. Please feel free to contribute the feature or advice on a way how this can be implemented with regards to IDEA plugin capabilities. But for now I'm going to close this issues it doesn't seem to be feasible to implement. Sorry for bringing bad news. :(
