### ISSUE TITLE
Add .env files by text input instead of file selection

### ISSUE THREAD

**Issue by iddan** [Ashald/EnvFile#62]
Classic `.env` file is hidden in UNIX systems (it starts with a `.`). I'd like to be able to easily write the path to the `.env` file without going through the FS.
Also, it should be clear also whether it's possible to use variables like `$PROJECT_DIR$` in the path.

**Comment by ashald** [comment]
While I understand your frustration with the UX, there are few tricks that make the experience better.

First of all, please take another look at the [README](https://github.com/Ashald/EnvFile#caveats) - if you're on macOS, there is a hot key that allows to switch easily between show/hide hidden files that works both in Finder and in open file dialog. In Linux-based distributions, I believe, there is a similar way to switch back and forth - though, that may vary on your window manager of choice.

As for typing while you cannot add an `.env` file just by typing at the moment, since the plugin does not filter files view by the extension you can add a random file and then manually adjust the path by double clicking on `Path` column as in screenshot below:
![screen shot 2018-05-21 at 21 06 32](https://user-images.githubusercontent.com/397987/40337114-98a23094-5d3b-11e8-800a-0bca170d4220.png)

While the path you will be editing is absolute, internally it's stored as a relative to `$PROJECT_DIR`. I just checked, it doesn't seem that you can type in relative path at the moment, but I'll see if I can add that to the next version of the plugin.
